<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\js\" />
    <Folder Include="wwwroot\lib\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CholitosAppFront.Core\CholitosAppFront.Core.csproj" />
    <ProjectReference Include="..\CholitosAppFront.Infrastructure\CholitosAppFront.Infrastructure.csproj" />
  </ItemGroup>

</Project>
