<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86</Platforms>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CholitosAppFront.Core\CholitosAppFront.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="libzkfpcsharp">
      <HintPath>bin\Debug\net8.0\libzkfpcsharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
